spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/todo
    url: jdbc:h2:~/todo

    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100